### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by kanohn** [SaiyansKing/Gothic-LegacyAltRenderer#1]
Sorry to post here, but i did not find any place to talk to you!

Sometime ago you made a custom 8.6 dll for me, and its working perfectly Thank God.

I have a great budget and i need to fix some little bugs (paying for each), and (if you have time) do others things.

Do you have any place that i can talk to you?

Anyway, please contact me at least for us to talk! Discord: kanohn#8348

**Comment by SaiyansKing** [comment]
I'm sorry but I don't want to have anything to do with tibia anymore.
